//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarinasHandicraft
{
    public partial class users
    {
        protected global::System.Web.UI.WebControls.GridView UserGridView;
        protected global::System.Web.UI.WebControls.Literal Message;

        // Add User Modal Controls
        protected global::System.Web.UI.WebControls.TextBox addFirstName;
        protected global::System.Web.UI.WebControls.TextBox addLastName;
        protected global::System.Web.UI.WebControls.TextBox addUsername;
        protected global::System.Web.UI.WebControls.TextBox addPassword;
        protected global::System.Web.UI.WebControls.TextBox addConfirmPassword;
        protected global::System.Web.UI.WebControls.DropDownList addGender;
        protected global::System.Web.UI.WebControls.DropDownList addRole;
        protected global::System.Web.UI.WebControls.DropDownList addStatus;

        // Update User Modal Controls
        protected global::System.Web.UI.WebControls.HiddenField hiddenUserId;
        protected global::System.Web.UI.WebControls.HiddenField hiddenUsername;
        protected global::System.Web.UI.WebControls.TextBox editFirstName;
        protected global::System.Web.UI.WebControls.TextBox editLastName;
        protected global::System.Web.UI.WebControls.DropDownList editGender;
        protected global::System.Web.UI.WebControls.DropDownList editRole;
        protected global::System.Web.UI.WebControls.DropDownList editStatus;

        // Delete User Modal Controls
        protected global::System.Web.UI.WebControls.HiddenField deleteUserId;
        protected global::System.Web.UI.WebControls.HiddenField deleteUsername;
    }
}
